- name: add setup files
  ansible.builtin.copy:
    src: caddy/
    dest: /etc/docker/caddy/
    owner: root
    group: root
    mode: "644"
  notify:
    - restart caddy

- name: add the caddy config files
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "/etc/docker/caddy/Caddyfile"
    owner: root
    group: root
    mode: "600"
  notify:
    - restart caddy

- name: start the service
  community.docker.docker_compose_v2:
    project_src: /etc/docker/caddy
    wait: true
    wait_timeout: 300
    state: present
