- name: remove DNS stub listener
  ansible.builtin.lineinfile:
    dest: /etc/systemd/resolved.conf
    regexp: '^(#\s*)?DNSStubListener.*'
    line: "DNSStubListener=no"
    state: present
    backup: true
  notify: restart resolved

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: create the directory if required
  ansible.builtin.file:
    path: /etc/docker/bind9/config
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: copy config files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/docker/bind9/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - "docker-compose.yml"
  notify:
    - restart the service again

- name: render zone files
  ansible.builtin.template:
    src: zone-template.j2
    dest: "/etc/docker/bind9/config/{{ item.name }}.zone"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ bind9_zone }}"
  when: bind9_master
  notify:
    - restart the service again

- name: render TSIG keys
  ansible.builtin.template:
    src: tsig-keys-template.j2
    dest: /etc/docker/bind9/config/tsig.keys
    owner: root
    group: root
    mode: "0600"
  when: bind9_master
  notify:
    - restart the service again

- name: render zone master
  ansible.builtin.template:
    src: zone-master-template.j2
    dest: /etc/docker/bind9/config/zone-master.conf
    owner: root
    group: root
    mode: "0644"
  when: bind9_master
  notify:
    - restart the service again

- name: render zone slave
  ansible.builtin.template:
    src: zone-slave-template.j2
    dest: /etc/docker/bind9/config/zone-slave.conf
    owner: root
    group: root
    mode: "0644"
  when: bind9_slave
  notify:
    - restart the service again

- name: render named conf
  ansible.builtin.template:
    src: master-named-conf.j2
    dest: /etc/docker/bind9/config/named.conf
    owner: root
    group: root
    mode: "0644"
  when: bind9_master
  notify:
    - restart the service again

- name: render named conf
  ansible.builtin.template:
    src: slave-named-conf.j2
    dest: /etc/docker/bind9/config/named.conf
    owner: root
    group: root
    mode: "0644"
  when: bind9_slave
  notify:
    - restart the service again

- name: start the service
  community.docker.docker_compose_v2:
    project_src: /etc/docker/bind9
    wait: true
    wait_timeout: 300
    state: present
