- name: create config directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0700"
  with_items:
    - "{{ cloudyhome_base_path }}"
    - /etc/sops/age
    - /etc/ssh-keysign

- name: copy systemd unit files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: "644"
  notify: restart resolved
  with_items:
    - cloudyhome-sync.service
    - cloudyhome-provision@.service

- name: copy git sync script
  ansible.builtin.template:
    src: git-sync.sh
    dest: "{{ cloudyhome_base_path }}/git-sync.sh"
    owner: root
    group: root
    mode: "750"
