---
- name: install required packages
  ansible.builtin.apt:
    name:
      - gpg
      - python3-debian
    state: present

- name: add repository into sources list
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}"
    suites: "{{ ansible_facts['lsb'].codename }}"
    components: stable
    signed_by: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg"
    state: present

- name: install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - python3
      - python3-docker
    state: present
    update_cache: true

- name: restart docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
