immich_db_password: ENC[AES256_GCM,data:1Qrj8SbucJIWsbBMW5o7Cv4/XRACSii1ZvvjQKUf,iv:vveyxdHh4PqsBy2/TBaihISysc3FLfly/ZCnig18Tjw=,tag:/15JwMbt1We/SASgfMnGfw==,type:str]
immich_nfs_server: ENC[AES256_GCM,data:ZNSjNMb3VFnxK4WUvb2c+FVjLApPCf0=,iv:EegZy+H+ALaI1AZtkSkhI5Ucprk3OPVZ6WTqOUE5JMI=,tag:x8a+QlUzZF0VDyszKv8qlQ==,type:str]
immich_nfs_export: ENC[AES256_GCM,data:CvdL5mInMZO+iFY26i4HKR0iFtmql5KSbcs=,iv:5TRi4fqn/UwTZXOU3clxw0zYZG9RXWAEDZ7Vi4Ffh9w=,tag:2sCIzfCfO6ImKc+s+8TwKA==,type:str]
sops:
  age:
    - recipient: age1c98gzcp0g5uhtvxec4pg6vpld5ukfx8e6c7vnnldmz3ahw2gxg7sap9jv9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MjBMb2VBZHZEbVZBQWNC
        S0N1MjJiUjFRVk5sRWo3YmtDVDIvU3M1bXgwCmV6SVZQc2lsSHl5TEI0bFRwWFlj
        R0FVK0JyRVIzTDcwSkVmNHFaY1NKRzAKLS0tIFZIUlhhb1J0UDJWMlZkRGxRRDM2
        azZrc3VPR09UTTE5dVRLYUg0THFRZjQKFGcOkJGJFTQmKiQhyMi0PognQuYjSnSS
        tE5sHawsJiHfXUm9ReUwPVH3iyvb8avzalVVU4uKakGFnklbERg77Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-29T09:42:20Z"
  mac: ENC[AES256_GCM,data:6zPNBUSCsRZz915OGCgpyZBgUckJ2VHlx0q1zGgKgLlFY/uuDrwYzaYPeS53f/SlhFFdOSQiTav4G1qRvnIqdRDQ5dX5JnShIBV9hvlUIQDRln9SdITx4dFDgrG849iJi1adLmzoRldEycBZ5nre2a9F3v5xQdER16+5nswgz20=,iv:tVJZMoDGZ8gtxFmsV0DrjRWggtQhqp7Sn4qBFWeSDV4=,tag:m9fR1VDVW/7WDfaMY/ejOw==,type:str]
  encrypted_regex: .*
  version: 3.11.0
