immich_db_password: ENC[AES256_GCM,data:ePPAY9x5CYzbczFGw0wqD3poKGJojrCpng==,iv:09mab9rr7ddOYRfuq2LHKyBB/lF0AFWavZFCvtvjGS4=,tag:PbsCbH5LkaFtl5rry9WsQA==,type:str]
immich_nfs_server: ENC[AES256_GCM,data:I7HP3Bs+kYE9wTvyZaUGXefCDanV/Cg=,iv:0qI3/AjrBXs0dWJBas4o4FSsUrB2nwqajEBQHw2fB3k=,tag:YU03Z8zO1m9Mu6AL5KfaDg==,type:str]
immich_nfs_export: ENC[AES256_GCM,data:6163KEYjwoCledOTg3Xkb731BzwE+zF1a8I=,iv:uFfYG/Jm4gUeWXuDLR+CTtNS60cyswX78kRbTCYJQik=,tag:hsH9qv22VCRsdQr4t2b6Zg==,type:str]
sops:
  age:
    - recipient: age1c98gzcp0g5uhtvxec4pg6vpld5ukfx8e6c7vnnldmz3ahw2gxg7sap9jv9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeFJ2OERhT0llU3N2QmFC
        WU5QWnF5OGVsWUN0Mi9mRTV1ellyTVZxclNZCnFKc3QyK0NNU1NnYXZ5d04vVjRr
        cElDUE5WNDZDME9nMHdyd040SGhGeGcKLS0tIFNVcUpnTGJqWmNkejRTTG9VNXV4
        bHBlOXRzK1R4akJZbXNjbXRTcUlkc1kKv04gZ1szQ/b7cPtPsQuFM+IMPI4kFkfD
        59txsC07O4T3Bm0K6y7jWI483642Xq3EF5M9gMPkjG3mrZ6IMVCy6A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-29T10:03:14Z"
  mac: ENC[AES256_GCM,data:rU8VW5wvYh1T36hdx8/qgjEigDQiBTkGsY4RocDpXNVZ7E7c7o9oaKkBSZu10L86y5ZDVk77VISABYsicfbwo0Cc2+upE5BcyJDrk3Vom6pIPaLrqzmy7taxVa8QG3nmmBv0Dm6TKiakF1ljqGy2LDqH2SfQPTLD53Ij5qoXq7Y=,iv:CLyWYAIREkvwR0+H8kbsR13Et+9ufGkzEpX7bTzN4v8=,tag:/obvlofZraU3AqmaROeO9w==,type:str]
  encrypted_regex: .*
  version: 3.11.0
