immich_db_password: ENC[AES256_GCM,data:8HPNTO9xaFqjMoUvF+17nUhcpsIaSiLSOA==,iv:pLAoM7jD5njrkE7gqkzkorINgHEYVpN8v6jqvOTNZiI=,tag:wNgAcOoMOMi+p71oX+2rZw==,type:str]
immich_nfs_server: ENC[AES256_GCM,data:2t73uhbKQn7EERaHnNQopLUNupnE3bU=,iv:XClpNHfzV6H4lqSO0T4gNuAZNSV2vIgVyQN561gik3s=,tag:/Vk3irerb1TfHTnWlvwcOw==,type:str]
immich_nfs_export: ENC[AES256_GCM,data:1446m2hSVZjy3Vtpqs/XnCEeeJlWcHEmBfM=,iv:JGjcQmeiEREIDnynUQnkHHl6ua2us6OEaA9pJ7gKLII=,tag:r66gcugV09C5yL+0OzjJ+g==,type:str]
immich_server_url: ENC[AES256_GCM,data:b8V7l9eK3iNhPARbv9pTbZ+A7e/rZa0ByGV4J+I=,iv:r7c1NTKqphekq+U117harx2SX6TKMvP0BSLo/V618H4=,tag:i63X95/4Wu7S6yntlYWQQA==,type:str]
immich_frame_api_key: ENC[AES256_GCM,data:fJ9kJ3BSKhLKnFb5a3935xTsIg5jO0WU1vnWd2cPXMuKBG8dVMOQCo5r,iv:m9c6Ni8WKVSr/1MehWVpyketCwnkomS9l4v858mSzWQ=,tag:XdGAQIbLuMnkp/m5Za7iIQ==,type:str]
sops:
  age:
    - recipient: age1c98gzcp0g5uhtvxec4pg6vpld5ukfx8e6c7vnnldmz3ahw2gxg7sap9jv9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2YVRQWFlyZ1Y4dXlMOXRw
        akdDbFlaMGdhdkNjTytzWkIzSlBSYVNkbjFBCnFHb3REVHBvZFpFcDBmNGpJZUVs
        M29aNlh6QUtiaDR2NmRubjBYN1ZoUncKLS0tIERyUTVCOGRsMUZTb1ZmQmhGbHhZ
        MG5wQzZqN29GcXZVUGJFTm5WQ2tCVjgK8i02fXevuOlMhWIw8Fo7LD3fA5aH9wvt
        AQcXlZ1H5rbosvCoGxXXHqSiBqVsc9aA/Z6EfEqLnDDCgae0UTvmZA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-14T11:29:50Z"
  mac: ENC[AES256_GCM,data:zC5IajLhCIMBw0IAtTYJlhh8oIOQFaFEUUs8uOTOABXdOxV/hY5uyrH39YW4lz1gcCGgaqhmhwLoRrGxuyK021ctY70sacZ7ArT8YL6hp/d0ADv76aB4IJd2FeiXUmDEHCta0pf5q2SgdaTHjAB8nRjGFguCn/oORXXXJDXF5uk=,iv:3Q3VDSJskVo+eTHve0sBoJLDs6relVFvoHiCbFhFiIk=,tag:voPZU4er/43A+cAQAZCgEw==,type:str]
  encrypted_regex: .*
  version: 3.11.0
